jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: BudgetKeeper