name: Feature pipeline

on: push

jobs:
  build:
    name: Build
    env:
      SCHEME: "BudgetKeeper"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Build application
      run: |
        set -o pipefail && xcodebuild clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
    - name: Upload products
      uses: actions/upload-artifact@v1
      with:
        name: Products
        path: DerivedData/Build/Products

  unit_test:
    name: Unit test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UNIT_TEST_TARGET: "BudgetKeeperTests"
    runs-on: macOS-latest
    needs: build
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        set -o pipefail && xcodebuild test-without-building -xctestrun $UNIT_TEST_TARGET -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UNIT_TEST_TARGET | xcpretty --color --simple
    - name: Upload test logs
      uses: actions/upload-artifact@v1

  ui_test:
    name: UI test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UI_TEST_TARGET: "BudgetKeeperUITests"
    runs-on: macOS-latest
    needs: build
    steps:
    - name: Checkout project 
      uses: actions/checkout@v1
    - name: Run UI tests
      run: |
        set -o pipefail && xcodebuild test-without-building -xctestrun $UI_TEST_TARGET -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UI_TEST_TARGET | xcpretty  --color --simple